### ISSUE TITLE
The generated subscription address import into clash-meta reports an error, can this place be supported?

### ISSUE THREAD

**Issue by serevrs** [MHSanaei/3x-ui#1977]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

The generated subscription address import into clash-meta reports an error, can this place be supported? In addition, when the connection is in use, saving the settings is not a problem, restarting the panel prompts a network error, if you close the online connection, restarting the panel is normal.

### Version of 3x-ui

<details>

```console
# Paste here
```

</details>

### x-ui log reports or xray log

<details>

```console
# paste log here
```

</details>
